### ISSUE TITLE
git URL suggestion

### ISSUE THREAD

**Issue by twpayne** [mkasberg/dotfiles#1]
Right now `README.md` contains:

```markdown
5. Fix the git origin in the chezmoi directory.
     ```
     $ chezmoi cd
     $ git remote set-url origin git@github.com:mkasberg/dotfiles.git
     ```
```

Consider adding this to your `~/.gitconfig`:

```
[url "git@github.com:mkasberg/"]
        insteadOf = https://github.com/mkasberg/
```

This means that:

* Before you have a `~/.gitconfig` you'll clone from `https://github.com/mkasberg/dotfiles.git`.
* Once you have a `~/.gitconfig` (managed with chezmoi, of course :) ) then you'll push/pull from `git@github.com:mkasberg/dotfiles.git`

Hope this helps - and thanks for Strava :)

**Comment by twpayne** [comment]
Oh, and also:

```
  3. Initialize chezmoi. Use https since we don't have creds yet.
     ```
     $ bin/chezmoi init https://github.com/mkasberg/dotfiles.git
     ```

  4. Install the dotfiles.
     ```
     $ chezmoi apply
     ```
```

can be achieved with:

```
bin/chezmoi init --apply https://github.com/mkasberg/dotfiles.git
```

**Comment by mkasberg** [comment]
Thanks, and thanks for chezmoi! Just using it for the first time today but loving it so far!
