### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by elgalu** [mkasberg/dotfiles#2]
Hi, thanks for sharing, could you add a license? e.g. MIT<3

**Comment by mkasberg** [comment]
This is a great suggestion. I'd be happy to release anything I can under the MIT license. One potential snag is that some of my dotfiles are based primarily on config installed by other open source projects (e.g. my `.zshrc` is slightly modified from the one installed by Oh My Zsh), so I'll need to look into the proper way to handle that with licensing. Let me do a little reading and get back to you.

**Comment by mkasberg** [comment]
After looking through my dotfiles, most are either my own config or derived from MIT licensed config (e.g. Oh My Zsh). There were only a couple files that were questionable, so I put together a LICENSE that releases most files under the MIT license and calls out the exceptions. :slightly_smiling_face:

**Comment by elgalu** [comment]
thanks a lot for your Christmas gift<3
